spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:sqlserver://127.0.0.1:9876;encrypt=true;columnEncryptionSetting=Enabled;keyStoreAuthentication=JavaKeyStorePassword;keyStoreLocation=keystore.jks;keyStoreSecret=mypassword
  liquibase:
    enabled: true